---
- name: "apt : Configure /etc/apt/apt.conf"
  template:
    src: "apt/apt.conf.j2"
    dest: "/etc/apt/apt.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "apt : Update package list"
  apt:
    update_cache: yes
