---
- name: "dnsmasq : Use the latest packages"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
      - dnsmasq
  notify: "dnsmasq : Restart"

- name: "dnsmasq : Configure /etc/dnsmasq.conf"
  template:
    src: "dnsmasq/dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "dnsmasq : Restart"

- name: "dnsmasq : Configure /etc/dnsmasq.d/<site>.conf"
  vars:
    dhcp: "{{ item.dhcp }}"
  template:
    src: "dnsmasq/site.conf.j2"
    dest: "/etc/dnsmasq.d/{{ item.name }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ sites }}"
  notify: "dnsmasq : Restart"

- name: "dnsmasq : Create directory /var/dnsmasq"
  file:
    dest: "/var/dnsmasq"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"

#
# PXELINUX
#
- name: "dnsmasq : Create directory /var/dnsmasq/pxelinux.cfg"
  file:
    dest: "/var/dnsmasq/pxelinux.cfg"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"

- name: "dnsmasq : Configure /var/dnsmasq/pxelinux.cfg/default"
  copy:
    src: "dnsmasq/pxelinux/default"
    dest: "/var/dnsmasq/pxelinux.cfg/default"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "dnsmasq : Upload /var/dnsmasq/pxelinux.0"
  copy:
    src: "dnsmasq/pxelinux/pxelinux.0"
    dest: "/var/dnsmasq/pxelinux.0"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "dnsmasq : Upload /var/dnsmasq/linux"
  copy:
    src: "dnsmasq/pxelinux/linux"
    dest: "/var/dnsmasq/linux"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "dnsmasq : Upload /var/dnsmasq/initrd.gz"
  copy:
    src: "dnsmasq/pxelinux/initrd.gz"
    dest: "/var/dnsmasq/initrd.gz"
    owner: "root"
    group: "root"
    mode: "0644"
