---
- name: "dnsmasq : Use the latest packages"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
      - dnsmasq
  notify: "dnsmasq : Restart"

- name: "dnsmasq : Configure /etc/default/dnsmasq"
  template:
    src: "dnsmasq/default-dnsmasq.j2"
    dest: "/etc/default/dnsmasq"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "dnsmasq : Restart"

- name: "dnsmasq : Configure /etc/dnsmasq.conf"
  template:
    src: "dnsmasq/dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "dnsmasq : Restart"

- name: "dnsmasq : Configure /etc/dnsmasq.d/<site>.conf"
  vars:
    dhcp: "{{ item.dhcp }}"
  template:
    src: "dnsmasq/site.conf.j2"
    dest: "/etc/dnsmasq.d/{{ item.name }}.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ sites }}"
  notify: "dnsmasq : Restart"

- name: "dnsmasq : Create directories"
  file:
    dest: "{{ item }}"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"
  with_items:
    - "/var/dnsmasq"
    - "/var/dnsmasq/pxelinux.cfg"
    - "/var/dnsmasq/preseed"

- name: "dnsmasq : Configure /var/dnsmasq/pxelinux.cfg/default"
  template:
    src: "dnsmasq/pxelinux.cfg.j2"
    dest: "/var/dnsmasq/pxelinux.cfg/default"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "dnsmasq : Upload PXELINUX binaries"
  copy:
    src: "dnsmasq/pxelinux/{{ item }}"
    dest: "/var/dnsmasq/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - initrd.gz
    - linux
    - pxelinux.0

- name: "dnsmasq : Configure /var/dnsmasq/preseed/default.seed"
  template:
    src: "dnsmasq/default.seed.j2"
    dest: "/var/dnsmasq/preseed/default.seed"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "dnsmasq : Start at boot"
  service:
    name: "{{ item }}"
    state: "started"
    enabled: yes
  with_items:
    - "dnsmasq"
