---
- name: "nginx : Use the latest packages"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - nginx
  notify: "nginx : Restart"

- name: "nginx : Start at boot"
  service:
    name: "{{ item }}"
    state: "started"
    enabled: yes
  with_items:
    - nginx
